---
  # Call with variables:
  #
  # * `name`: The name of the files to copy
  # * `src`
  # * `dest`
  # * `tmpname`: Temporary name on the remote host
  # * `changed_when`: Override changed_when condition of copy tasks

  - name: Create remote directory
    become: "{{ 'no' if local_ca_is_to_local else 'yes' }}"
    file:
      path: "{{ dest | dirname }}"
      state: directory
      owner: "{{ omit if local_ca_is_to_local_same_user else local_ca_owner }}"
      group: "{{ omit if local_ca_is_to_local_same_user else local_ca_group }}"
      mode: u+rwx

  - name: Copy {{ name }} to node
    become: "{{ 'no' if local_ca_is_to_local else 'yes' }}"
    when: local_ca_is_local and changed_when is not defined
    copy:
      src: "{{ src }}"
      dest: "{{ dest }}"
      owner: "{{ omit if local_ca_is_to_local_same_user else local_ca_owner }}"
      group: "{{ omit if local_ca_is_to_local_same_user else local_ca_group }}"
      mode: "{{ omit if local_ca_is_to_local_same_user else local_ca_mode }}"

  - name: Copy {{ name }} to node
    become: "{{ 'no' if local_ca_is_to_local else 'yes' }}"
    when: local_ca_is_local and changed_when is defined
    copy:
      src: "{{ src }}"
      dest: "{{ dest }}"
      owner: "{{ omit if local_ca_is_to_local_same_user else local_ca_owner }}"
      group: "{{ omit if local_ca_is_to_local_same_user else local_ca_group }}"
      mode: "{{ omit if local_ca_is_to_local_same_user else local_ca_mode }}"
    changed_when: changed_when|bool

  - name: Fetch {{ name }} to control node
    when: not local_ca_is_local
    fetch:
      src: "{{ src }}"
      dest: "{{ local_ca_fetchdir }}/{{ tmpname }}"
      flat: yes
      validate_checksum: yes
      fail_on_missing: yes
    delegate_to: "{{ local_ca_workhost }}"
    changed_when: False

  - name: Upload {{ name }} to target node
    when: not local_ca_is_local and not ansible_check_mode and changed_when is not defined
    become: "{{ 'no' if local_ca_is_to_local else 'yes' }}"
    copy:
      src: "{{ local_ca_fetchdir }}/{{ tmpname }}"
      dest: "{{ dest }}"
      owner: "{{ omit if local_ca_is_to_local_same_user else local_ca_owner }}"
      group: "{{ omit if local_ca_is_to_local_same_user else local_ca_group }}"
      mode: "{{ omit if local_ca_is_to_local_same_user else local_ca_mode }}"

  - name: Upload {{ name }} to target node
    when: not local_ca_is_local and not ansible_check_mode and changed_when is defined
    become: "{{ 'no' if inventory_hostname == 'local' else 'yes' }}"
    copy:
      src: "{{ local_ca_fetchdir }}/{{ tmpname }}"
      dest: "{{ dest }}"
      owner: "{{ omit if local_ca_is_to_local_same_user else local_ca_owner }}"
      group: "{{ omit if local_ca_is_to_local_same_user else local_ca_group }}"
      mode: "{{ omit if local_ca_is_to_local_same_user else local_ca_mode }}"
    changed_when: changed_when|bool
